/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/commands/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record one control-plane command intent.
         * @description The kind, the target and the desired state are checked against the domain's own
         *     compatibility matrix before anything is written, and the revision is checked
         *     against what the aggregate currently stands at — so a caller working from a
         *     stale read is told the current revision and nothing is mutated. The write
         *     itself is `kontor-store`'s single transaction: intent, target row, outbox
         *     entry, first durable transition, desired state and the intent event, or none of
         *     them.
         */
        post: operations["command"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The durable control-plane feed.
         * @description Three properties make it restartable. Every frame's SSE `id` is the event's
         *     own persisted control-plane cursor, so `Last-Event-ID` is a position this
         *     Realm actually allocated. Delivery is strictly greater than the requested
         *     position, so nothing is repeated and nothing is skipped. And the events come
         *     from SQLite rather than from memory, so a reconnect after a restart reads the
         *     same log the previous connection was reading.
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness, Realm identity and the startup barrier. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One task, its active workflow, its gate states and its pinned revisions. */
        get: operations["task_snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/realm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This Realm's immutable identity. */
        get: operations["realm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{agent_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One agent run, its projection, its pinned revisions and its recorded gaps. */
        get: operations["run_snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{agent_run_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deliver one message into a session.
         * @description The `Idempotency-Key` *is* the stable client message id: it must parse as one,
         *     and it is what the runtime's own ledger keys the effect on. Requiring two
         *     separate tokens would create two things that can disagree about whether a
         *     retry is the same message, and only one of them would be the one the runtime
         *     actually checks.
         */
        post: operations["send_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{agent_run_id}/permissions/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer one permission request raised inside a session. */
        post: operations["respond_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{agent_run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Follow a session's content strictly after a validated timeline anchor.
         * @description The anchor is required, and that is the transport spelling of "history anchors
         *     live": without a position a previous read validated, there is nothing for
         *     delivery to be strictly after, and a stream that guessed would be unable to
         *     tell a runtime dropping events from its own missing start.
         */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{agent_run_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One page of a session's recorded content, read from the runtime.
         * @description The page is validated through `HistoryReader` before it is returned, so what a
         *     caller receives is exactly-once by construction: a redelivered item is dropped
         *     from the page rather than merely uncounted, and a page that changes epoch,
         *     skips a sequence or rewrites a position it already delivered is refused.
         */
        get: operations["timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The JSON body every refusal is reported with. */
        ApiErrorBody: {
            /** @description The stable machine-readable code. */
            code: string;
            /**
             * Format: int64
             * @description The revision the aggregate actually stands at, for a revision conflict.
             */
            current_revision?: number | null;
            /**
             * Format: int64
             * @description The newest position allocated, for a resnapshot.
             */
            newest_cursor?: number | null;
            /**
             * Format: int64
             * @description The oldest position still retained, for a resnapshot.
             */
            oldest_retained_cursor?: number | null;
            /** @description The Realm the request was refused in. */
            realm_id: string;
            /** @description A static description of the rule that refused. Never a stored value. */
            rule: string;
        };
        /**
         * @description Which pinned specification revisions an aggregate is running under.
         *
         *     Every one of these is a *frozen* revision copied into the aggregate, not a
         *     pointer to whatever the current definition happens to be. That is what makes
         *     a snapshot re-checkable rather than merely re-readable.
         */
        AppliedRevisionsDto: {
            /** @description The persona scenario frozen onto the task, if any. */
            persona_scenario?: string | null;
            /**
             * Format: int32
             * @description That scenario's revision.
             */
            persona_scenario_version?: number | null;
            /** @description The team template the run's team pinned. */
            team_template?: string | null;
            /**
             * Format: int32
             * @description That template's revision.
             */
            team_template_version?: number | null;
            /** @description The work profile the task's active workflow pinned. */
            work_profile?: string | null;
            /**
             * Format: int32
             * @description That profile's revision.
             */
            work_profile_version?: number | null;
        };
        /**
         * @description How far startup reconciliation has got, and therefore whether scheduling may
         *     run.
         * @enum {string}
         */
        BarrierState: "pending" | "open" | "failed";
        /** @description The native session one run is bound to, as evidence and never as identity. */
        BindingDto: {
            /**
             * @description Whether this process still holds the frozen capability snapshot for it,
             *     and can therefore address the session at all.
             */
            attached: boolean;
            /** @description The Kontor binding. */
            binding_id: string;
            /**
             * Format: date-time
             * @description When it was bound.
             */
            bound_at: string;
            /**
             * Format: int64
             * @description The runtime generation the session belongs to.
             */
            generation: number;
            /** @description The host label the runtime reports for itself. */
            host: string;
            /** @description The runtime's own session id. Correlation evidence. */
            native_id: string;
            /** @description The runtime family. Never an endpoint. */
            runtime_kind: string;
        };
        /** @description What a command asks for, as a caller states it. */
        CommandRequest: {
            /** @description The desired run state, for the commands that carry one. */
            desired_state?: string | null;
            /**
             * Format: int64
             * @description The revision the caller computed the intent against.
             */
            expected_revision: number;
            /** @description The canonical intent document. Must carry a `schema_version`. */
            intent: Record<string, never>;
            /** @description The canonical dispatch payload. Must carry a `schema_version`. */
            payload: Record<string, never>;
            /** @description The acting project. */
            project_id: string;
            /** @description The aggregate the command targets. */
            target: Record<string, never>;
        };
        /** @description One durable control-plane event. */
        EventDto: {
            /** @description The run it concerns. */
            agent_run_id: string;
            /**
             * Format: int64
             * @description Its control-plane position.
             */
            cursor: number;
            /**
             * Format: int64
             * @description The runtime generation it belongs to.
             */
            generation: number;
            /** @description The runtime's own event id, when it provides one. */
            native_event_id?: string | null;
            /** @description The runtime's own session id. */
            native_id: string;
            /**
             * Format: int64
             * @description The runtime's own ordering.
             */
            native_sequence: number;
            /**
             * Format: date-time
             * @description When the runtime emitted it.
             */
            observed_at: string;
            /**
             * @description The stored control metadata. Held to the store's positive allowlist, so it
             *     is facts about the session and never the session's content.
             */
            payload: Record<string, never>;
            /** @description The project that owns it. */
            project_id: string;
            /** @description The Realm it was recorded in. */
            realm_id: string;
            /**
             * Format: date-time
             * @description When this Realm stored it.
             */
            recorded_at: string;
            /** @description The runtime family that reported it. */
            runtime_kind: string;
        };
        /** @description A recorded discontinuity a reader is owed. */
        GapDto: {
            /**
             * Format: int64
             * @description The runtime's content epoch, for a content gap.
             */
            content_epoch?: number | null;
            /**
             * Format: date-time
             * @description When it was noticed.
             */
            detected_at: string;
            /**
             * Format: int64
             * @description The control-plane position the hole was noticed at.
             */
            detected_cursor: number;
            /**
             * Format: int64
             * @description The sequence that was expected next.
             */
            expected_sequence: number;
            /** @description Which cursor space the hole is in. */
            kind: string;
            /**
             * Format: int64
             * @description The sequence that actually arrived.
             */
            received_sequence: number;
        };
        /** @description Liveness, identity and how far startup has got. */
        HealthDto: {
            /** @description Always true: reaching a handler is what liveness means. */
            live: boolean;
            /** @description The Realm answering. */
            realm_id: string;
            /**
             * @description Whether startup reconciliation finished, and therefore whether scheduling
             *     is open.
             */
            reconciliation: components["schemas"]["BarrierState"];
            /** @description The runtime families this daemon was configured with. */
            runtimes: string[];
            /** @description Whether work may be dispatched right now. */
            scheduling_open: boolean;
            /**
             * Format: int64
             * @description The persisted schema generation.
             */
            schema_version: number;
        };
        /** @description The runtime's answer to one delivered message. */
        MessageAckDto: {
            /**
             * Format: date-time
             * @description When the runtime accepted it.
             */
            accepted_at: string;
            /** @description The binding it was delivered into. */
            binding_id: string;
            /**
             * Format: int64
             * @description The content epoch it landed in.
             */
            epoch: number;
            /**
             * @description The Kontor identifier the message was sent under. It is the
             *     `Idempotency-Key` the caller presented.
             */
            message_id: string;
            /**
             * Format: int64
             * @description Where it landed inside that epoch.
             */
            sequence: number;
        };
        /** @description What a caller sends into a session. */
        MessageRequest: {
            /** @description The message body. */
            body: string;
        };
        /** @description The runtime's answer to one permission response. */
        PermissionAckDto: {
            /**
             * Format: date-time
             * @description When the runtime accepted it.
             */
            accepted_at: string;
            /** @description The binding whose session raised the request. */
            binding_id: string;
            /** @description The answer that was applied. */
            decision: string;
            /**
             * Format: int64
             * @description The content epoch the resolution landed in.
             */
            epoch: number;
            /** @description The runtime's own identifier for the request that was answered. */
            permission_id: string;
            /** @description The Kontor identifier the answer was sent under. */
            response_id: string;
            /**
             * Format: int64
             * @description Where it landed inside that epoch.
             */
            sequence: number;
        };
        /** @description How a permission request is answered. */
        PermissionRequestBody: {
            /** @description The answer. */
            decision: string;
        };
        /** @description The orthogonal state of one run, plus how old its newest confirmation is. */
        ProjectionDto: {
            /** @description What Kontor concluded. `terminal` carries its outcome separately. */
            derived: string;
            /** @description What Kontor asked for. */
            desired: string;
            /**
             * @description How old that confirmation is, judged against the daemon's evidence window
             *     at the instant this snapshot was taken.
             */
            freshness: string;
            /**
             * Format: date-time
             * @description When the newest trusted confirmation arrived.
             */
            last_confirmed_at?: string | null;
            /**
             * Format: int64
             * @description The control-plane position of the newest reduced event.
             */
            last_cursor?: number | null;
            /** @description The run's own lifecycle. */
            lifecycle: string;
            /** @description What the runtime last reported. */
            observed: string;
            /** @description The outcome, when the run is closed. */
            outcome?: string | null;
        };
        /** @description This Realm's immutable identity. */
        RealmDto: {
            /**
             * Format: date-time
             * @description When it was created.
             */
            created_at: string;
            /** @description Its optional non-secret label. */
            display_label?: string | null;
            /** @description The Realm. */
            realm_id: string;
            /**
             * Format: int32
             * @description The envelope contract it was created under.
             */
            schema_version: number;
        };
        /** @description The durable record of one command. */
        ReceiptDto: {
            /**
             * Format: int32
             * @description How many dispatch attempts have been made.
             */
            attempts: number;
            /**
             * Format: date-time
             * @description When the intent was recorded.
             */
            created_at: string;
            /** @description The caller's idempotency key. */
            idempotency_key: string;
            /** @description What was asked for. */
            kind: string;
            /** @description The project that owns it. */
            project_id: string;
            /** @description The receipt. */
            receipt_id: string;
            /** @description How far it has got. An acknowledgement is never a completion. */
            state: string;
            /** @description Which aggregate it targets. */
            target: Record<string, never>;
            /**
             * Format: int64
             * @description The revision the intent was computed against.
             */
            target_revision: number;
            /**
             * Format: date-time
             * @description When the receipt last changed.
             */
            updated_at: string;
        };
        /** @description A receipt, and whether this call is the one that recorded it. */
        ReceiptResponse: Record<string, never> & {
            /**
             * @description `true` when the idempotency key had already recorded this exact command,
             *     so nothing was written and the original receipt is being returned.
             */
            replayed: boolean;
        };
        /** @description One agent run, as a cross-boundary reader sees it. */
        RunDto: {
            /** @description The coding account it is pinned to, if any. */
            account_profile_id?: string | null;
            /** @description The run. */
            agent_run_id: string;
            /** @description The team template revision this run's team pinned. */
            applied: components["schemas"]["AppliedRevisionsDto"];
            binding?: null | components["schemas"]["BindingDto"];
            /**
             * Format: date-time
             * @description When it closed.
             */
            closed_at?: string | null;
            /**
             * Format: date-time
             * @description When it was created.
             */
            created_at: string;
            /** @description Every recorded discontinuity, oldest first. */
            gaps: components["schemas"]["GapDto"][];
            /** @description The run it succeeds, for recovery and resume. */
            parent_agent_run_id?: string | null;
            /** @description The project it belongs to. */
            project_id: string;
            /** @description The orthogonal state. */
            projection: components["schemas"]["ProjectionDto"];
            /**
             * Format: int64
             * @description The revision a write must present.
             */
            revision: number;
            /** @description The role slot it fills. */
            role: string;
            /** @description The team run it serves. */
            team_run_id: string;
        };
        /**
         * @description A point-in-time value and the position it is consistent with.
         *
         *     It is the wire spelling of `kontor-core`'s own `SnapshotEnvelope`: a
         *     subscriber resumes strictly after `snapshot_cursor`, in the same Realm.
         */
        SnapshotDto_RunDto: {
            /** @description The Realm this snapshot came from. */
            realm_id: string;
            /**
             * Format: int64
             * @description The position it is consistent with.
             */
            snapshot_cursor: number;
            /** @description One agent run, as a cross-boundary reader sees it. */
            value: {
                /** @description The coding account it is pinned to, if any. */
                account_profile_id?: string | null;
                /** @description The run. */
                agent_run_id: string;
                /** @description The team template revision this run's team pinned. */
                applied: components["schemas"]["AppliedRevisionsDto"];
                binding?: null | components["schemas"]["BindingDto"];
                /**
                 * Format: date-time
                 * @description When it closed.
                 */
                closed_at?: string | null;
                /**
                 * Format: date-time
                 * @description When it was created.
                 */
                created_at: string;
                /** @description Every recorded discontinuity, oldest first. */
                gaps: components["schemas"]["GapDto"][];
                /** @description The run it succeeds, for recovery and resume. */
                parent_agent_run_id?: string | null;
                /** @description The project it belongs to. */
                project_id: string;
                /** @description The orthogonal state. */
                projection: components["schemas"]["ProjectionDto"];
                /**
                 * Format: int64
                 * @description The revision a write must present.
                 */
                revision: number;
                /** @description The role slot it fills. */
                role: string;
                /** @description The team run it serves. */
                team_run_id: string;
            };
        };
        /**
         * @description A point-in-time value and the position it is consistent with.
         *
         *     It is the wire spelling of `kontor-core`'s own `SnapshotEnvelope`: a
         *     subscriber resumes strictly after `snapshot_cursor`, in the same Realm.
         */
        SnapshotDto_TaskDto: {
            /** @description The Realm this snapshot came from. */
            realm_id: string;
            /**
             * Format: int64
             * @description The position it is consistent with.
             */
            snapshot_cursor: number;
            /** @description One task, its active workflow and the gates reduced from its evaluations. */
            value: {
                /** @description The pinned specification revisions in force. */
                applied: components["schemas"]["AppliedRevisionsDto"];
                /** @description The phase the active workflow is in. */
                current_phase?: string | null;
                /** @description The gate states, keyed by gate. */
                gates: Record<string, never>;
                /** @description The project it belongs to. */
                project_id: string;
                /**
                 * Format: int64
                 * @description The revision a write must present.
                 */
                revision: number;
                /** @description Its lifecycle state. */
                state: string;
                /** @description The task. */
                task_id: string;
                /** @description Its title. */
                title: string;
                /**
                 * Format: date-time
                 * @description When it last changed.
                 */
                updated_at: string;
            };
        };
        /**
         * @description One frame of live session content.
         *
         *     The item is wrapped rather than sent bare so that *every* frame of the stream
         *     carries the Realm and the run it belongs to — a console holding two sessions
         *     open must never have to infer which one a frame came from.
         */
        StreamFrameDto: {
            /** @description The run whose session produced it. */
            agent_run_id: string;
            /** @description The content item. */
            item: components["schemas"]["TimelineItemDto"];
            /** @description The Realm the session belongs to. */
            realm_id: string;
        };
        /**
         * @description A frame the live-content stream emits instead of an item when the timeline can
         *     no longer be followed.
         */
        StreamRefusalDto: {
            /** @description Always `timeline_refetch_required`. */
            code: string;
            /** @description The Realm the session belongs to. */
            realm_id: string;
            /** @description A static description of what broke. */
            rule: string;
        };
        /** @description One task, its active workflow and the gates reduced from its evaluations. */
        TaskDto: {
            /** @description The pinned specification revisions in force. */
            applied: components["schemas"]["AppliedRevisionsDto"];
            /** @description The phase the active workflow is in. */
            current_phase?: string | null;
            /** @description The gate states, keyed by gate. */
            gates: Record<string, never>;
            /** @description The project it belongs to. */
            project_id: string;
            /**
             * Format: int64
             * @description The revision a write must present.
             */
            revision: number;
            /** @description Its lifecycle state. */
            state: string;
            /** @description The task. */
            task_id: string;
            /** @description Its title. */
            title: string;
            /**
             * Format: date-time
             * @description When it last changed.
             */
            updated_at: string;
        };
        /** @description One page of a session's recorded content. */
        TimelineDto: {
            /** @description The run whose session was read. */
            agent_run_id: string;
            /**
             * @description The cursor a live subscription resumes from. The same position as
             *     `end_epoch`/`end_sequence`, in the form `/stream` accepts.
             */
            anchor: string;
            /**
             * Format: int64
             * @description The last position this page covers. A live subscription must start
             *     strictly after it.
             */
            end_epoch: number;
            /**
             * Format: int64
             * @description The sequence half of that position.
             */
            end_sequence: number;
            /**
             * Format: int64
             * @description The runtime's content epoch every item belongs to.
             */
            epoch: number;
            /** @description The items, in ascending sequence order. */
            items: components["schemas"]["TimelineItemDto"][];
            /** @description Where to continue, or `null` when the history is exhausted. */
            next?: string | null;
            /** @description The Realm the session belongs to. */
            realm_id: string;
        };
        /** @description One item of session content. */
        TimelineItemDto: {
            /**
             * Format: date-time
             * @description When the runtime emitted it.
             */
            emitted_at: string;
            /**
             * Format: int64
             * @description Its position inside the epoch.
             */
            epoch: number;
            /** @description What kind of thing happened. */
            kind: string;
            /** @description The Kontor message id, when the item is about one. */
            message_id?: string | null;
            /** @description The runtime's own event id, when it provides one. */
            native_event_id?: string | null;
            /** @description The runtime's own payload. Never persisted by this control plane. */
            payload: Record<string, never>;
            /** @description The runtime's permission request id, when the item is about one. */
            permission_id?: string | null;
            /**
             * Format: int64
             * @description Its position inside that epoch.
             */
            sequence: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    command: {
        parameters: {
            query?: never;
            header: {
                /** @description The caller's stable key */
                "Idempotency-Key": string;
            };
            path: {
                /** @description The command kind */
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Recorded, or replayed unchanged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptResponse"];
                };
            };
            /** @description Stale revision or a reused idempotency key */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    events: {
        parameters: {
            query?: {
                /** @description Resume strictly after this cursor */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An SSE stream of control-plane events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The position is outside the retained history */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    task_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The owning project */
                project_id: string;
                /** @description The task */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDto_TaskDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    realm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealmDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Kontor agent run */
                agent_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDto_RunDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_message: {
        parameters: {
            query?: never;
            header: {
                /** @description The stable client message id */
                "Idempotency-Key": string;
            };
            path: {
                /** @description The Kontor agent run */
                agent_run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Delivered, or the original ack replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageAckDto"];
                };
            };
            /** @description The id already committed different content */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This runtime cannot take messages */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    respond_permission: {
        parameters: {
            query?: never;
            header: {
                /** @description The stable client response id */
                "Idempotency-Key": string;
            };
            path: {
                /** @description The Kontor agent run */
                agent_run_id: string;
                /** @description The runtime's own permission request id */
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionRequestBody"];
            };
        };
        responses: {
            /** @description Applied, or the original ack replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionAckDto"];
                };
            };
            /** @description The request was already answered differently */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This runtime cannot take permission answers */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stream: {
        parameters: {
            query: {
                /** @description The anchor a timeline read returned */
                after: string;
            };
            header?: never;
            path: {
                /** @description The Kontor agent run */
                agent_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An SSE stream of session content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No anchor was presented */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This runtime cannot stream content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    timeline: {
        parameters: {
            query?: {
                /** @description A runtime continuation cursor */
                after?: string;
                /** @description Maximum items */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description The Kontor agent run */
                agent_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineDto"];
                };
            };
            /** @description The timeline must be refetched from the start */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This runtime cannot replay content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
