//! Identity, versioning, canonical data and hashes.
//!
//! Three families of identifier exist and are never interchangeable:
//!
//! * **Entity ids** — UUID v7 newtypes generated by Kontor, persisted as
//!   lowercase hyphenated text.
//! * **Open keys** — deployment-defined names (`WorkProfileKey`, `PhaseKey`, …).
//!   They follow one conservative lexical rule so they are safe in paths, URLs,
//!   SQL and JSON; the core never enumerates their values.
//! * **External strings** — names and ids owned by a foreign system
//!   ([`ExternalName`], [`ExternalId`]). They are Unicode, may contain spaces
//!   and are *never* forced through the internal-key rule.

use std::collections::BTreeSet;
use std::fmt;

use serde::de::Error as _;
use serde::ser::Error as _;
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use sha2::{Digest, Sha256};
use uuid::Uuid;

use crate::{DomainError, DomainResult};

pub use jiff::Timestamp;

/// Maximum length of an internal open key, in characters.
pub const MAX_KEY_LEN: usize = 128;
/// Maximum length of an external display name, in characters.
pub const MAX_EXTERNAL_NAME_LEN: usize = 512;
/// Maximum length of an opaque external identifier, in characters.
pub const MAX_EXTERNAL_ID_LEN: usize = 256;
/// Maximum length of a bounded free-text value, in characters.
pub const MAX_TEXT_LEN: usize = 65_536;
/// Maximum serialized size of a canonical document, in bytes.
pub const MAX_CANONICAL_BYTES: usize = 1_048_576;
/// Maximum nesting depth of a canonical document.
pub const MAX_CANONICAL_DEPTH: usize = 32;

// ---------------------------------------------------------------------------
// Entity ids
// ---------------------------------------------------------------------------

macro_rules! entity_ids {
    ($( $(#[$meta:meta])* $name:ident ),+ $(,)?) => {
        $(
            $(#[$meta])*
            ///
            /// A time-ordered UUID v7 generated by Kontor and persisted as
            /// lowercase hyphenated text.
            #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
            pub struct $name(Uuid);

            impl $name {
                /// Generate a fresh, time-ordered identifier.
                #[must_use]
                pub fn generate() -> Self {
                    Self(Uuid::now_v7())
                }

                /// Parse the canonical lowercase hyphenated text form.
                ///
                /// # Errors
                /// Rejects any non-canonical spelling and any UUID that is not
                /// version 7.
                pub fn parse(text: &str) -> DomainResult<Self> {
                    parse_entity_uuid(stringify!($name), text).map(Self)
                }

                /// Borrow the underlying UUID.
                #[must_use]
                pub const fn as_uuid(&self) -> &Uuid {
                    &self.0
                }
            }

            impl fmt::Display for $name {
                fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                    fmt::Display::fmt(&self.0.as_hyphenated(), f)
                }
            }

            impl Serialize for $name {
                fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                    serializer.serialize_str(&self.to_string())
                }
            }

            impl<'de> Deserialize<'de> for $name {
                fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                    let text = String::deserialize(deserializer)?;
                    Self::parse(&text).map_err(D::Error::custom)
                }
            }
        )+
    };
}

entity_ids! {
    /// Identifies one Realm: one database file / state root, and therefore one
    /// isolation boundary.
    ///
    /// A Realm id is *not* a tenant column. Domain tables never repeat it; the
    /// file itself is the boundary. It exists so that a snapshot, event, receipt
    /// or export leaving the process can be read as `(realm_id, entity_id)`
    /// rather than as an unqualified id that means something else in another
    /// Realm.
    RealmId,
    /// Identifies one project (the tenant boundary inside a Kontor database).
    ProjectId,
    /// Identifies a goal-sized unit of work inside a project.
    MiniProjectId,
    /// Identifies a task.
    TaskId,
    /// Identifies the resolved work-profile instance attached to a task.
    TaskWorkflowId,
    /// Identifies a team template (its revisions share this id).
    TeamTemplateId,
    /// Identifies one run of a team.
    TeamRunId,
    /// Identifies one run of a single agent.
    AgentRunId,
    /// Identifies the binding between an agent run and a native runtime session.
    RuntimeBindingId,
    /// Identifies a context pack handed to a run.
    ContextPackId,
    /// Identifies a handoff between phases or agents.
    HandoffId,
    /// Identifies a coding-account profile that runs may be pinned to.
    AccountProfileId,
    /// Identifies the link between a task and one external ticket.
    TicketLinkId,
    /// Identifies one immutable revision of an external-ticket projection.
    TicketProjectionId,
    /// Identifies one append-only observation of an external ticket.
    TicketObservationId,
    /// Identifies one attempt to converge an external ticket's status/assignee.
    StatusTransitionReceiptId,
    /// Identifies an unresolved or resolved external-status conflict.
    StatusConflictId,
    /// Identifies one append-only guardrail evaluation.
    GuardrailEvaluationId,
    /// Identifies a lease over a contended resource (a module, a worktree, …).
    ResourceLeaseId,
    /// Identifies one command intent and its receipt.
    CommandReceiptId,
    /// Identifies one canonical inbound source event.
    SourceEventId,
    /// Identifies one intake decision for a source event.
    IntakeReceiptId,
    /// Identifies a workspace-level calendar profile (its revisions share this id).
    CalendarProfileId,
    /// Identifies a project's calendar assignment.
    WorkCalendarId,
    /// Identifies one retrieved holiday source revision.
    HolidaySourceId,
    /// Identifies one append-only calendar exception revision.
    CalendarExceptionId,
    /// Identifies an execution authorization that arms ready work.
    ExecutionAuthorizationId,
    /// Identifies a bounded schedule override.
    ScheduleOverrideId,
    /// Identifies a persona scenario (its revisions share this id).
    PersonaScenarioId,
}

fn parse_entity_uuid(subject: &'static str, text: &str) -> DomainResult<Uuid> {
    let uuid = Uuid::try_parse(text)
        .map_err(|_| DomainError::invalid(subject, "not a UUID in canonical text form"))?;
    if uuid.get_version_num() != 7 {
        return Err(DomainError::invalid(subject, "not a version 7 UUID"));
    }
    if uuid.as_hyphenated().to_string() != text {
        return Err(DomainError::invalid(
            subject,
            "not lowercase hyphenated canonical form",
        ));
    }
    Ok(uuid)
}

// ---------------------------------------------------------------------------
// Open keys
// ---------------------------------------------------------------------------

/// Validate one internal open key against the single lexical rule.
///
/// The rule is: 1–128 characters, ASCII only, first character `[a-z0-9]`,
/// remainder `[a-z0-9._-]`. That rejects uppercase, whitespace, control
/// characters, path separators, empty input and any input whose trimmed form
/// differs from itself.
///
/// # Errors
/// Returns [`DomainError::Invalid`] naming `subject`; the offending value is
/// never included.
pub fn validate_open_key(subject: &'static str, text: &str) -> DomainResult<()> {
    if text.is_empty() {
        return Err(DomainError::invalid(subject, "must not be empty"));
    }
    if text.chars().count() > MAX_KEY_LEN {
        return Err(DomainError::invalid(subject, "longer than 128 characters"));
    }
    let mut chars = text.chars();
    let first = chars.next().unwrap_or('\0');
    if !first.is_ascii_lowercase() && !first.is_ascii_digit() {
        return Err(DomainError::invalid(
            subject,
            "must start with a lowercase ASCII letter or digit",
        ));
    }
    for character in chars {
        let allowed = character.is_ascii_lowercase()
            || character.is_ascii_digit()
            || matches!(character, '.' | '_' | '-');
        if !allowed {
            return Err(DomainError::invalid(
                subject,
                "may contain only lowercase ASCII letters, digits, '.', '_' and '-'",
            ));
        }
    }
    reject_sensitive_text(subject, text)
}

macro_rules! open_keys {
    ($( $(#[$meta:meta])* $name:ident ),+ $(,)?) => {
        $(
            $(#[$meta])*
            ///
            /// An open, deployment-defined key. See [`validate_open_key`] for the
            /// lexical rule; the core never enumerates the legal values.
            #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
            pub struct $name(String);

            impl $name {
                /// Parse and validate an open key.
                ///
                /// # Errors
                /// See [`validate_open_key`].
                pub fn parse(text: &str) -> DomainResult<Self> {
                    validate_open_key(stringify!($name), text)?;
                    Ok(Self(text.to_owned()))
                }

                /// Borrow the key text.
                #[must_use]
                pub fn as_str(&self) -> &str {
                    &self.0
                }
            }

            impl fmt::Display for $name {
                fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                    f.write_str(&self.0)
                }
            }

            impl Serialize for $name {
                fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                    serializer.serialize_str(&self.0)
                }
            }

            impl<'de> Deserialize<'de> for $name {
                fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                    let text = String::deserialize(deserializer)?;
                    Self::parse(&text).map_err(D::Error::custom)
                }
            }
        )+
    };
}

open_keys! {
    /// Names a work profile (a phase DAG plus its gates and contracts).
    WorkProfileKey,
    /// Names a phase inside a work profile.
    PhaseKey,
    /// Names a gate inside a work profile.
    GateKey,
    /// Names a role that a team member or evaluator can hold.
    RoleKey,
    /// Names a skill a role may require.
    SkillKey,
    /// Names an artifact a phase must produce or a gate must consume.
    ArtifactKey,
    /// Names a trigger specification.
    TriggerKey,
    /// Names an external connector implementation (never its vendor semantics).
    ConnectorKey,
    /// Names a project in the external system.
    ExternalProjectKey,
    /// Names an issue type in the external system.
    ExternalIssueTypeKey,
    /// Names an internal, semantic milestone that external statuses map to.
    SemanticMilestoneKey,
    /// Names a module or code area that work can contend for.
    ModuleKey,
    /// Names a kind of inbound event source.
    SourceKindKey,
    /// Names one configured connection of a source kind.
    SourceConnectionKey,
    /// Names a runtime family (an agent runtime, not one of its sessions).
    RuntimeKindKey,
    /// Names the schema of an inbound source event payload.
    EventSchemaKey,
    /// Names a simulated persona used by a persona scenario.
    PersonaKey,
    /// Names one approved credential reference, and nothing about where it
    /// resolves to.
    ///
    /// The alias is the *whole* stored reference: a config-home directory, a
    /// keychain service/account pair and a token value are resolver-owned and
    /// never persisted. An alias that the resolver policy does not already
    /// approve resolves to nothing, so an alias is not a capability.
    CredentialAlias,
}

// ---------------------------------------------------------------------------
// External (foreign-owned) strings
// ---------------------------------------------------------------------------

fn reject_control_characters(subject: &'static str, text: &str) -> DomainResult<()> {
    if text
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\n' | '\t'))
    {
        return Err(DomainError::invalid(
            subject,
            "must not contain control characters",
        ));
    }
    Ok(())
}

/// A display name owned by an external system.
///
/// Unicode, may contain spaces, must be non-empty, trimmed, free of control
/// characters and at most [`MAX_EXTERNAL_NAME_LEN`] characters. External status
/// names, labels and human names use this type; they are never open keys.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ExternalName(String);

impl ExternalName {
    /// Parse an external display name.
    ///
    /// # Errors
    /// Rejects empty, untrimmed, oversized or control-bearing input.
    pub fn parse(text: &str) -> DomainResult<Self> {
        if text.is_empty() || text.trim() != text {
            return Err(DomainError::invalid(
                "ExternalName",
                "must be non-empty and free of leading or trailing whitespace",
            ));
        }
        if text.chars().count() > MAX_EXTERNAL_NAME_LEN {
            return Err(DomainError::invalid(
                "ExternalName",
                "longer than 512 characters",
            ));
        }
        if text.chars().any(char::is_control) {
            return Err(DomainError::invalid(
                "ExternalName",
                "must not contain control characters",
            ));
        }
        reject_sensitive_text("ExternalName", text)?;
        Ok(Self(text.to_owned()))
    }

    /// Borrow the name text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// An opaque identifier owned by an external system.
///
/// External status ids, transition ids, issue keys, comment ids and account ids
/// are opaque to Kontor: their content is data, never a branch condition.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ExternalId(String);

impl ExternalId {
    /// Parse an opaque external identifier.
    ///
    /// # Errors
    /// Rejects empty, oversized, whitespace-bearing or control-bearing input.
    pub fn parse(text: &str) -> DomainResult<Self> {
        if text.is_empty() {
            return Err(DomainError::invalid("ExternalId", "must not be empty"));
        }
        if text.chars().count() > MAX_EXTERNAL_ID_LEN {
            return Err(DomainError::invalid(
                "ExternalId",
                "longer than 256 characters",
            ));
        }
        if text.chars().any(char::is_whitespace) {
            return Err(DomainError::invalid(
                "ExternalId",
                "must not contain whitespace",
            ));
        }
        if text.chars().any(char::is_control) {
            return Err(DomainError::invalid(
                "ExternalId",
                "must not contain control characters",
            ));
        }
        reject_sensitive_text("ExternalId", text)?;
        Ok(Self(text.to_owned()))
    }

    /// Borrow the identifier text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// The *name* of one environment variable a child process is given.
///
/// A name is not a value: this type exists so that the one non-secret half of a
/// credential mapping has somewhere to live that can be persisted, listed and
/// put in a receipt, while the value it will carry never has a persisted type at
/// all.
///
/// The rule is the POSIX portable one — `[A-Z_][A-Z0-9_]*`, at most
/// [`MAX_KEY_LEN`] characters — which rules out `=`, whitespace, path
/// separators and the lowercase spellings a shell treats differently.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct EnvironmentVariableName(String);

impl EnvironmentVariableName {
    /// Parse an environment variable name.
    ///
    /// # Errors
    /// Rejects empty, oversized, lowercase, digit-leading and punctuation-
    /// bearing input, and anything [`reject_sensitive_text`] refuses.
    pub fn parse(text: &str) -> DomainResult<Self> {
        if text.is_empty() {
            return Err(DomainError::invalid(
                "EnvironmentVariableName",
                "must not be empty",
            ));
        }
        if text.chars().count() > MAX_KEY_LEN {
            return Err(DomainError::invalid(
                "EnvironmentVariableName",
                "longer than 128 characters",
            ));
        }
        let mut characters = text.chars();
        let first = characters.next().unwrap_or('\0');
        if !first.is_ascii_uppercase() && first != '_' {
            return Err(DomainError::invalid(
                "EnvironmentVariableName",
                "must start with an uppercase ASCII letter or '_'",
            ));
        }
        for character in characters {
            if !character.is_ascii_uppercase() && !character.is_ascii_digit() && character != '_' {
                return Err(DomainError::invalid(
                    "EnvironmentVariableName",
                    "may contain only uppercase ASCII letters, digits and '_'",
                ));
            }
        }
        reject_sensitive_text("EnvironmentVariableName", text)?;
        Ok(Self(text.to_owned()))
    }

    /// Borrow the name text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// A bounded free-text value (a field body, a comment body, a label).
///
/// Line endings are normalized to `\n` so the same content always hashes the
/// same way regardless of the platform that produced it.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BoundedText(String);

impl BoundedText {
    /// Parse and normalize a bounded text value.
    ///
    /// # Errors
    /// Rejects oversized input and control characters other than `\n` and `\t`.
    pub fn parse(text: &str) -> DomainResult<Self> {
        let normalized = normalize_line_endings(text);
        if normalized.chars().count() > MAX_TEXT_LEN {
            return Err(DomainError::invalid(
                "BoundedText",
                "longer than 65536 characters",
            ));
        }
        reject_control_characters("BoundedText", &normalized)?;
        reject_sensitive_text("BoundedText", &normalized)?;
        Ok(Self(normalized))
    }

    /// Borrow the normalized text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Normalize CRLF and lone CR to LF.
#[must_use]
pub fn normalize_line_endings(text: &str) -> String {
    if !text.contains('\r') {
        return text.to_owned();
    }
    let mut out = String::with_capacity(text.len());
    let mut chars = text.chars().peekable();
    while let Some(character) = chars.next() {
        if character == '\r' {
            if chars.peek() == Some(&'\n') {
                chars.next();
            }
            out.push('\n');
        } else {
            out.push(character);
        }
    }
    out
}

macro_rules! bounded_string_serde {
    ($($name:ident),+ $(,)?) => {
        $(
            impl fmt::Display for $name {
                fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                    f.write_str(&self.0)
                }
            }

            impl Serialize for $name {
                fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                    serializer.serialize_str(&self.0)
                }
            }

            impl<'de> Deserialize<'de> for $name {
                fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                    let text = String::deserialize(deserializer)?;
                    Self::parse(&text).map_err(D::Error::custom)
                }
            }
        )+
    };
}

bounded_string_serde!(
    ExternalName,
    ExternalId,
    BoundedText,
    IdempotencyKey,
    EnvironmentVariableName
);

// ---------------------------------------------------------------------------
// Versions, revisions, cursors
// ---------------------------------------------------------------------------

/// The persisted schema generation this binary understands.
///
/// Schema v1 accepts only `1`. A document or database claiming a newer schema is
/// refused rather than guessed at.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(transparent)]
pub struct SchemaVersion(u32);

/// The one schema version this binary implements.
pub const SCHEMA_VERSION: SchemaVersion = SchemaVersion(1);

impl SchemaVersion {
    /// Accept a document/database schema version.
    ///
    /// # Errors
    /// Rejects `0` and anything newer than [`SCHEMA_VERSION`].
    pub fn parse(value: u32) -> DomainResult<Self> {
        if value == 0 {
            return Err(DomainError::invalid("SchemaVersion", "must be positive"));
        }
        if value > SCHEMA_VERSION.0 {
            return Err(DomainError::invalid(
                "SchemaVersion",
                "is newer than this binary understands",
            ));
        }
        Ok(Self(value))
    }

    /// The numeric value.
    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }
}

impl<'de> Deserialize<'de> for SchemaVersion {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Self::parse(u32::deserialize(deserializer)?).map_err(D::Error::custom)
    }
}

/// The version of one immutable specification revision.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(transparent)]
pub struct SpecVersion(u32);

impl SpecVersion {
    /// The first revision of any specification.
    pub const FIRST: Self = Self(1);

    /// Parse a positive specification version.
    ///
    /// # Errors
    /// Rejects `0`.
    pub fn parse(value: u32) -> DomainResult<Self> {
        if value == 0 {
            return Err(DomainError::invalid("SpecVersion", "must be positive"));
        }
        Ok(Self(value))
    }

    /// The numeric value.
    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }

    /// The next revision.
    ///
    /// # Errors
    /// Rejects overflow rather than wrapping.
    pub fn next(self) -> DomainResult<Self> {
        self.0
            .checked_add(1)
            .map(Self)
            .ok_or_else(|| DomainError::invalid("SpecVersion", "overflowed"))
    }
}

impl<'de> Deserialize<'de> for SpecVersion {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Self::parse(u32::deserialize(deserializer)?).map_err(D::Error::custom)
    }
}

/// The optimistic-concurrency revision of a mutable aggregate.
///
/// Starts at `1` and only ever moves forward through a compare-and-swap.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(transparent)]
pub struct AggregateRevision(u64);

impl AggregateRevision {
    /// The revision of a freshly created aggregate.
    pub const INITIAL: Self = Self(1);

    /// Parse a stored revision.
    ///
    /// # Errors
    /// Rejects `0`.
    pub fn parse(value: u64) -> DomainResult<Self> {
        if value == 0 {
            return Err(DomainError::invalid(
                "AggregateRevision",
                "must start at 1 and be positive",
            ));
        }
        Ok(Self(value))
    }

    /// The numeric value.
    #[must_use]
    pub const fn get(self) -> u64 {
        self.0
    }

    /// The revision that a successful compare-and-swap writes.
    ///
    /// # Errors
    /// Rejects overflow rather than wrapping.
    pub fn next(self) -> DomainResult<Self> {
        self.0
            .checked_add(1)
            .map(Self)
            .ok_or_else(|| DomainError::invalid("AggregateRevision", "overflowed"))
    }

    /// Check a caller's expectation against the stored revision.
    ///
    /// # Errors
    /// Returns [`DomainError::RevisionConflict`] when they differ.
    pub fn expect(self, subject: &'static str, expected: Self) -> DomainResult<()> {
        if self == expected {
            Ok(())
        } else {
            Err(DomainError::RevisionConflict {
                subject,
                expected: expected.0,
                found: self.0,
            })
        }
    }
}

impl<'de> Deserialize<'de> for AggregateRevision {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Self::parse(u64::deserialize(deserializer)?).map_err(D::Error::custom)
    }
}

/// A positive, monotonically increasing event cursor.
///
/// Cursors are allocated by the store (a SQLite `INTEGER PRIMARY KEY
/// AUTOINCREMENT`) and are never reused, so a subscriber can resume strictly
/// *after* the cursor it already saw.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(transparent)]
pub struct EventCursor(i64);

impl EventCursor {
    /// Parse a stored cursor.
    ///
    /// # Errors
    /// Rejects zero and negative values.
    pub fn parse(value: i64) -> DomainResult<Self> {
        if value <= 0 {
            return Err(DomainError::invalid("EventCursor", "must be positive"));
        }
        Ok(Self(value))
    }

    /// The numeric value.
    #[must_use]
    pub const fn get(self) -> i64 {
        self.0
    }
}

impl<'de> Deserialize<'de> for EventCursor {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Self::parse(i64::deserialize(deserializer)?).map_err(D::Error::custom)
    }
}

/// A caller-supplied idempotency key.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct IdempotencyKey(String);

impl IdempotencyKey {
    /// Parse an idempotency key.
    ///
    /// # Errors
    /// Rejects empty, untrimmed, oversized or control-bearing input.
    pub fn parse(text: &str) -> DomainResult<Self> {
        if text.is_empty() || text.trim() != text {
            return Err(DomainError::invalid(
                "IdempotencyKey",
                "must be non-empty and free of leading or trailing whitespace",
            ));
        }
        if text.chars().count() > MAX_EXTERNAL_ID_LEN {
            return Err(DomainError::invalid(
                "IdempotencyKey",
                "longer than 256 characters",
            ));
        }
        reject_control_characters("IdempotencyKey", text)?;
        reject_sensitive_text("IdempotencyKey", text)?;
        Ok(Self(text.to_owned()))
    }

    /// Borrow the key text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

// ---------------------------------------------------------------------------
// Money
// ---------------------------------------------------------------------------

/// An uppercase ISO-4217 currency code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct CurrencyCode([u8; 3]);

impl CurrencyCode {
    /// Parse a three-letter uppercase currency code.
    ///
    /// # Errors
    /// Rejects anything that is not exactly three uppercase ASCII letters.
    pub fn parse(text: &str) -> DomainResult<Self> {
        let bytes = text.as_bytes();
        if bytes.len() != 3 || !bytes.iter().all(u8::is_ascii_uppercase) {
            return Err(DomainError::invalid(
                "CurrencyCode",
                "must be three uppercase ASCII letters",
            ));
        }
        Ok(Self([bytes[0], bytes[1], bytes[2]]))
    }

    /// Borrow the code text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        // Constructed only from validated ASCII.
        std::str::from_utf8(&self.0).unwrap_or("XXX")
    }
}

impl fmt::Display for CurrencyCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Serialize for CurrencyCode {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for CurrencyCode {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let text = String::deserialize(deserializer)?;
        Self::parse(&text).map_err(D::Error::custom)
    }
}

/// A monetary amount in integer minor units.
///
/// Money is never a floating-point value anywhere in Kontor, in Rust or in
/// SQLite.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct Money {
    /// Amount in the currency's minor units (for example: øre, cents).
    pub minor_units: u64,
    /// The currency the minor units are denominated in.
    pub currency: CurrencyCode,
}

// ---------------------------------------------------------------------------
// Timestamps
// ---------------------------------------------------------------------------

/// Parse a canonical UTC RFC 3339 timestamp.
///
/// The text must already be canonical UTC: a value that parses but renders
/// differently (an offset, a lowercase `z`, a redundant fraction) is rejected
/// rather than silently normalized, so stored text and in-memory value always
/// agree.
///
/// # Errors
/// Returns [`DomainError::Invalid`] for unparsable or non-canonical input.
pub fn parse_utc_timestamp(text: &str) -> DomainResult<Timestamp> {
    let timestamp: Timestamp = text
        .parse()
        .map_err(|_| DomainError::invalid("Timestamp", "not an RFC 3339 timestamp"))?;
    if timestamp.to_string() != text {
        return Err(DomainError::invalid(
            "Timestamp",
            "not in canonical UTC RFC 3339 form",
        ));
    }
    Ok(timestamp)
}

/// Render a timestamp in the canonical UTC form used for persistence.
#[must_use]
pub fn format_utc_timestamp(timestamp: Timestamp) -> String {
    timestamp.to_string()
}

// ---------------------------------------------------------------------------
// Hashes and canonical documents
// ---------------------------------------------------------------------------

/// A lowercase SHA-256 hex digest.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ContentHash(String);

impl ContentHash {
    /// Hash arbitrary bytes.
    #[must_use]
    pub fn of(bytes: &[u8]) -> Self {
        let mut hasher = Sha256::new();
        hasher.update(bytes);
        Self(hex::encode(hasher.finalize()))
    }

    /// Parse a stored digest.
    ///
    /// # Errors
    /// Rejects anything that is not 64 lowercase hex characters.
    pub fn parse(text: &str) -> DomainResult<Self> {
        if text.len() != 64
            || !text
                .bytes()
                .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
        {
            return Err(DomainError::invalid(
                "ContentHash",
                "must be 64 lowercase hexadecimal characters",
            ));
        }
        Ok(Self(text.to_owned()))
    }

    /// Borrow the digest text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ContentHash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl Serialize for ContentHash {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&self.0)
    }
}

impl<'de> Deserialize<'de> for ContentHash {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let text = String::deserialize(deserializer)?;
        Self::parse(&text).map_err(D::Error::custom)
    }
}

/// A validated, canonically serialized JSON document and its digest.
///
/// Canonical form is: compact UTF-8, object keys sorted, array order preserved,
/// `\n` line endings inside strings, no non-finite numbers, a top-level object
/// carrying `schema_version`, bounded depth and bounded size. The document is
/// stored byte-for-byte together with [`ContentHash`] of exactly those bytes, so
/// a reordered or re-indented copy is detected instead of silently accepted.
///
/// Construction also rejects credential-, token- and identity-bearing material,
/// so an unredacted source envelope or persona document cannot reach SQL.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CanonicalDocument {
    json: String,
    hash: ContentHash,
    schema_version: SchemaVersion,
}

impl CanonicalDocument {
    /// Canonicalize, validate and hash a JSON value.
    ///
    /// # Errors
    /// Returns [`DomainError`] when the value is not a `schema_version`-bearing
    /// object, exceeds the depth/size bounds, contains a non-finite number or
    /// carries sensitive material.
    pub fn from_value(value: &serde_json::Value) -> DomainResult<Self> {
        let schema_version = read_schema_version(value)?;
        reject_sensitive_material(value)?;
        let mut json = String::new();
        write_canonical(value, 0, &mut String::new(), &mut json)?;
        if json.len() > MAX_CANONICAL_BYTES {
            return Err(DomainError::invalid(
                "CanonicalDocument",
                "larger than 1 MiB once canonicalized",
            ));
        }
        let hash = ContentHash::of(json.as_bytes());
        Ok(Self {
            json,
            hash,
            schema_version,
        })
    }

    /// Canonicalize any serializable value.
    ///
    /// # Errors
    /// As [`CanonicalDocument::from_value`], plus serialization failures.
    pub fn from_serializable<T: Serialize>(value: &T) -> DomainResult<Self> {
        let value = serde_json::to_value(value).map_err(|_| {
            DomainError::invalid("CanonicalDocument", "is not serializable as JSON")
        })?;
        Self::from_value(&value)
    }

    /// Re-admit a document read back from storage, verifying both its canonical
    /// form and its recorded digest.
    ///
    /// # Errors
    /// Returns [`DomainError`] when the stored bytes are not canonical or the
    /// digest does not match.
    pub fn from_stored(json: &str, hash: &ContentHash) -> DomainResult<Self> {
        let value: serde_json::Value = serde_json::from_str(json)
            .map_err(|_| DomainError::invalid("CanonicalDocument", "is not valid JSON"))?;
        let document = Self::from_value(&value)?;
        if document.json != json {
            return Err(DomainError::invalid(
                "CanonicalDocument",
                "stored bytes are not in canonical form",
            ));
        }
        if &document.hash != hash {
            return Err(DomainError::invalid(
                "CanonicalDocument",
                "stored digest does not match the stored bytes",
            ));
        }
        Ok(document)
    }

    /// The canonical bytes, exactly as persisted.
    #[must_use]
    pub fn json(&self) -> &str {
        &self.json
    }

    /// The digest of [`CanonicalDocument::json`].
    #[must_use]
    pub const fn hash(&self) -> &ContentHash {
        &self.hash
    }

    /// The `schema_version` declared by the document.
    #[must_use]
    pub const fn schema_version(&self) -> SchemaVersion {
        self.schema_version
    }

    /// Parse the document back into a typed value.
    ///
    /// # Errors
    /// Returns [`DomainError`] when the document does not match `T`.
    pub fn deserialize<T: for<'de> Deserialize<'de>>(&self) -> DomainResult<T> {
        serde_json::from_str(&self.json).map_err(|_| {
            DomainError::invalid("CanonicalDocument", "does not match the target type")
        })
    }
}

impl Serialize for CanonicalDocument {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let value: serde_json::Value = serde_json::from_str(&self.json)
            .map_err(|_| S::Error::custom("canonical document is not valid JSON"))?;
        value.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for CanonicalDocument {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = serde_json::Value::deserialize(deserializer)?;
        Self::from_value(&value).map_err(D::Error::custom)
    }
}

fn read_schema_version(value: &serde_json::Value) -> DomainResult<SchemaVersion> {
    let object = value.as_object().ok_or_else(|| {
        DomainError::invalid("CanonicalDocument", "top level must be a JSON object")
    })?;
    let raw = object.get("schema_version").ok_or_else(|| {
        DomainError::invalid("CanonicalDocument", "must declare `schema_version`")
    })?;
    let number = raw.as_u64().ok_or_else(|| {
        DomainError::invalid(
            "CanonicalDocument",
            "`schema_version` must be a positive integer",
        )
    })?;
    let narrowed = u32::try_from(number).map_err(|_| {
        DomainError::invalid("CanonicalDocument", "`schema_version` is out of range")
    })?;
    SchemaVersion::parse(narrowed)
}

fn write_canonical(
    value: &serde_json::Value,
    depth: usize,
    path: &mut String,
    out: &mut String,
) -> DomainResult<()> {
    if depth > MAX_CANONICAL_DEPTH {
        return Err(DomainError::invalid_at(
            "CanonicalDocument",
            path.clone(),
            "nested deeper than 32 levels",
        ));
    }
    match value {
        serde_json::Value::Null => out.push_str("null"),
        serde_json::Value::Bool(flag) => out.push_str(if *flag { "true" } else { "false" }),
        serde_json::Value::Number(number) => {
            if number.as_f64().is_some_and(|n| !n.is_finite()) {
                return Err(DomainError::invalid_at(
                    "CanonicalDocument",
                    path.clone(),
                    "contains a non-finite number",
                ));
            }
            out.push_str(&number.to_string());
        }
        serde_json::Value::String(text) => {
            let normalized = normalize_line_endings(text);
            let encoded = serde_json::to_string(&normalized).map_err(|_| {
                DomainError::invalid_at(
                    "CanonicalDocument",
                    path.clone(),
                    "contains an unencodable string",
                )
            })?;
            out.push_str(&encoded);
        }
        serde_json::Value::Array(items) => {
            out.push('[');
            for (index, item) in items.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                let restore = path.len();
                path.push_str(&format!("[{index}]"));
                write_canonical(item, depth + 1, path, out)?;
                path.truncate(restore);
            }
            out.push(']');
        }
        serde_json::Value::Object(members) => {
            let keys: BTreeSet<&String> = members.keys().collect();
            out.push('{');
            for (index, key) in keys.into_iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                let encoded = serde_json::to_string(key).map_err(|_| {
                    DomainError::invalid_at(
                        "CanonicalDocument",
                        path.clone(),
                        "contains an unencodable object key",
                    )
                })?;
                out.push_str(&encoded);
                out.push(':');
                let restore = path.len();
                if !path.is_empty() {
                    path.push('.');
                }
                path.push_str(key);
                let member = members.get(key).unwrap_or(&serde_json::Value::Null);
                write_canonical(member, depth + 1, path, out)?;
                path.truncate(restore);
            }
            out.push('}');
        }
    }
    Ok(())
}

/// Object keys that may never appear in a persisted document.
///
/// Matching is exact on the normalized key (lowercased, `-`/`_`/space removed),
/// so legitimate names such as `token_budget` or `max_tokens` are unaffected.
const FORBIDDEN_KEYS: &[&str] = &[
    "secret",
    "secrets",
    "password",
    "passwd",
    "pwd",
    "token",
    "accesstoken",
    "refreshtoken",
    "idtoken",
    "bearertoken",
    "sessiontoken",
    "apikey",
    "apisecret",
    "clientsecret",
    "authorization",
    "credential",
    "credentials",
    "privatekey",
    "cookie",
    "ssn",
    "nationalid",
    "socialsecuritynumber",
    "birthnumber",
    "personnummer",
    "fodselsnummer",
    "patientid",
    "patientname",
];

/// Markers that indicate credential material, paired with the minimum number of
/// characters that must follow them.
///
/// The tail length is what keeps this usable: `sk-skill` is a perfectly good
/// open key, while `sk-` followed by twenty-four more characters is an API
/// token. Marker matching is defence in depth, not a vault — see the plan's
/// security note.
const SECRET_MARKERS: &[(&str, usize)] = &[
    ("-----begin", 0),
    ("private key", 0),
    ("private-key", 0),
    // A separator is required so an ordinary word starting "bearer" is safe.
    ("bearer ", 20),
    ("bearer-", 20),
    ("bearer_", 20),
    ("bearer:", 20),
    ("basic ", 20),
    ("basic-", 20),
    ("ghp_", 20),
    ("gho_", 20),
    ("github_pat_", 20),
    ("glpat-", 16),
    ("xoxb-", 16),
    ("xoxp-", 16),
    ("sk-", 24),
    ("sk_live_", 16),
    ("akia", 16),
    ("asia", 16),
    ("aiza", 20),
];

/// Inline assignments that carry a credential in an otherwise ordinary string,
/// such as a connection string or a copied command line.
const SECRET_ASSIGNMENTS: &[&str] = &[
    "password=",
    "passwd=",
    "pwd=",
    "api_key=",
    "apikey=",
    "secret=",
    "client_secret=",
    "access_token=",
    "refresh_token=",
    "token=",
    "authorization:",
];

fn has_marker(lowered: &str, marker: &str, min_tail: usize) -> bool {
    lowered
        .match_indices(marker)
        .any(|(index, _)| lowered.len() - index - marker.len() >= min_tail)
}

/// Whether the text embeds a password in a URL's userinfo (`scheme://u:p@host`).
fn has_url_credentials(lowered: &str) -> bool {
    let Some(scheme_end) = lowered.find("://") else {
        return false;
    };
    let authority = &lowered[scheme_end + 3..];
    let authority = authority.split('/').next().unwrap_or(authority);
    match authority.split_once('@') {
        Some((userinfo, _)) => userinfo.contains(':'),
        None => false,
    }
}

/// Reject credential, token or key material in any persisted string.
///
/// This is the single primitive every persisted string category goes through:
/// open keys, external names and ids, bounded text, idempotency keys and every
/// JSON string all call it, so no string-bearing value reaches SQL unscanned.
///
/// # Errors
/// Returns [`DomainError::SensitiveMaterial`] carrying only `path` — the
/// candidate value is never echoed, so a canary cannot leak into a log or a
/// test assertion.
pub fn reject_sensitive_text(path: &str, text: &str) -> DomainResult<()> {
    if text.is_empty() {
        return Ok(());
    }
    let lowered = text.to_lowercase();
    let hit = SECRET_MARKERS
        .iter()
        .any(|(marker, min_tail)| has_marker(&lowered, marker, *min_tail))
        || SECRET_ASSIGNMENTS
            .iter()
            .any(|marker| lowered.contains(marker))
        || has_url_credentials(&lowered);
    if hit {
        return Err(DomainError::SensitiveMaterial {
            path: path.to_owned(),
        });
    }
    Ok(())
}

/// Reject credentials, tokens and unredacted personal identifiers.
///
/// # Errors
/// Returns [`DomainError::SensitiveMaterial`] carrying only the structural path
/// of the offending node.
pub fn reject_sensitive_material(value: &serde_json::Value) -> DomainResult<()> {
    fn walk(value: &serde_json::Value, path: &mut String) -> DomainResult<()> {
        match value {
            serde_json::Value::Object(members) => {
                for (key, member) in members {
                    let normalized: String = key
                        .chars()
                        .filter(|c| !matches!(c, '-' | '_' | ' '))
                        .flat_map(char::to_lowercase)
                        .collect();
                    let restore = path.len();
                    if !path.is_empty() {
                        path.push('.');
                    }
                    path.push_str(key);
                    if FORBIDDEN_KEYS.contains(&normalized.as_str()) {
                        return Err(DomainError::SensitiveMaterial { path: path.clone() });
                    }
                    walk(member, path)?;
                    path.truncate(restore);
                }
                Ok(())
            }
            serde_json::Value::Array(items) => {
                for (index, item) in items.iter().enumerate() {
                    let restore = path.len();
                    path.push_str(&format!("[{index}]"));
                    walk(item, path)?;
                    path.truncate(restore);
                }
                Ok(())
            }
            serde_json::Value::String(text) => reject_sensitive_text(path, text),
            _ => Ok(()),
        }
    }

    walk(value, &mut String::new())
}
