//! Runtime-neutral native containers, keyed by topology node.
//!
//! [`crate::workspace`] binds a native place to a *team run and task*. That is
//! the shape of the tracker, not the shape of the thing being placed: a TeamRun
//! is one delivery attempt at one ticket, while the native project it works in
//! outlives every run inside it. Keying a container that way makes the second
//! run of the same ticket look like a new place to put things, and it leaves
//! every container that no ticket owns — an epic root, a consultation, an
//! advisory workspace — unaddressable.
//!
//! So a container is keyed by [`TopologyNodeId`] and nothing else. The node is
//! durable, it exists before any run does, and it is the same node after a
//! restart. A task and a TeamRun may still travel with the request, but only as
//! metadata a runtime may use for display: neither is ever read back as the
//! identity of a native container.
//!
//! What shape the container takes is not the adapter's choice either. The
//! pinned specification revision declares each node kind's
//! [`NodeProjectionCapability`] set, and [`ContainerProjection::resolve`] turns
//! that set into the one shape the runtime must produce. An adapter that
//! branched on the kind *name* instead would be carrying a copy of the
//! Operational vocabulary that no specification revision can correct.

use std::fmt;

use kontor_core::id::{ExternalId, ExternalName, TaskId, TeamRunId, Timestamp, TopologyNodeId};
use kontor_core::spec::{NodeProjectionCapability, TopologySnapshot};
use kontor_core::state::NativeRuntimeIdentity;
use kontor_core::{DomainError, DomainResult};
use uuid::Uuid;

use crate::adapter::{RuntimeError, RuntimeResult};
use crate::capability::RuntimeCapabilities;
use crate::request::parse_kontor_uuid;
use crate::workspace::WorkspaceRoot;

/// The prefix every Kontor container correlation label carries.
pub const CONTAINER_CORRELATION_PREFIX: &str = "kontor-node-";

/// Identifies the binding between a topology node and one native container.
///
/// A time-ordered UUID v7 generated by Kontor and rendered as lowercase
/// hyphenated text.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ContainerBindingId(Uuid);

impl ContainerBindingId {
    /// Generate a fresh, time-ordered identifier.
    #[must_use]
    pub fn generate() -> Self {
        Self(kontor_core::id::generate_uuid_v7())
    }

    /// Parse the canonical lowercase hyphenated text form.
    ///
    /// # Errors
    /// Rejects any non-canonical spelling and any UUID that is not version 7,
    /// which is what stops a native container id from being read as one.
    pub fn parse(text: &str) -> DomainResult<Self> {
        parse_kontor_uuid("ContainerBindingId", text).map(Self)
    }

    /// Borrow the underlying UUID.
    #[must_use]
    pub const fn as_uuid(&self) -> &Uuid {
        &self.0
    }
}

impl fmt::Display for ContainerBindingId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Display::fmt(&self.0.as_hyphenated(), f)
    }
}

/// A label Kontor plants so a native container can be tied back to the topology
/// node that owns it.
///
/// The label *is* a [`TopologyNodeId`] by construction, so a native container id
/// can never be parsed into one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ContainerLabel(TopologyNodeId);

impl ContainerLabel {
    /// The label for one topology node.
    #[must_use]
    pub const fn for_node(topology_node_id: TopologyNodeId) -> Self {
        Self(topology_node_id)
    }

    /// Parse a label a runtime reported back.
    ///
    /// # Errors
    /// Returns [`DomainError::Invalid`] when the text is not the Kontor prefix
    /// followed by a canonical [`TopologyNodeId`].
    pub fn parse(text: &str) -> DomainResult<Self> {
        let tail = text
            .strip_prefix(CONTAINER_CORRELATION_PREFIX)
            .ok_or_else(|| {
                DomainError::invalid("ContainerLabel", "does not carry the Kontor node prefix")
            })?;
        TopologyNodeId::parse(tail).map(Self)
    }

    /// The topology node this label names.
    #[must_use]
    pub const fn topology_node_id(self) -> TopologyNodeId {
        self.0
    }
}

impl fmt::Display for ContainerLabel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{CONTAINER_CORRELATION_PREFIX}{}", self.0)
    }
}

/// Proof that a native container belongs to the topology node that owns it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContainerCorrelationEvidence {
    /// The Kontor label the runtime reported back.
    pub label: ContainerLabel,
    /// The native container that reported it. Evidence, never identity.
    pub native: NativeRuntimeIdentity,
    /// When the correlation was established.
    pub established_at: Timestamp,
}

impl ContainerCorrelationEvidence {
    /// Establish correlation from what a runtime reported.
    ///
    /// # Errors
    /// Returns [`RuntimeError::CorrelationFailed`] when the runtime did not
    /// report this node's label.
    pub fn establish(
        topology_node_id: TopologyNodeId,
        reported: &str,
        native: NativeRuntimeIdentity,
        established_at: Timestamp,
    ) -> RuntimeResult<Self> {
        let label = ContainerLabel::for_node(topology_node_id);
        if reported != label.to_string() {
            return Err(RuntimeError::CorrelationFailed);
        }
        Ok(Self {
            label,
            native,
            established_at,
        })
    }

    /// Correlate a container the runtime gives no way to label.
    ///
    /// Some containers have no label surface at all — Paseo's `project.add`
    /// carries none, and a project's display name is a mutable string an
    /// operator can change. For those the correlation *is* the exact id: this
    /// binding was made from a readback of that id and of nothing else.
    ///
    /// Only ever built from a readback. Constructing one from a desired id
    /// rather than an observed one would produce a snapshot that looks
    /// identical and proves nothing.
    #[must_use]
    pub const fn by_exact_id(
        topology_node_id: TopologyNodeId,
        native: NativeRuntimeIdentity,
        established_at: Timestamp,
    ) -> Self {
        Self {
            label: ContainerLabel::for_node(topology_node_id),
            native,
            established_at,
        }
    }
}

/// The one native shape a node's declared capabilities require.
///
/// This is the adapter's whole dispatch. It is derived from the pinned
/// specification's capability set rather than from the node's kind key, because
/// the kind vocabulary is data a specification revision owns and the shapes
/// below are the closed set a runtime can actually build.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ContainerProjection {
    /// No native container exists, and none is ever persisted or reconciled.
    LogicalOnly,
    /// The node materializes as a native root/project.
    NativeRoot,
    /// The node materializes below an exact native root.
    NativeChild,
}

impl ContainerProjection {
    /// Resolve the shape a validated capability set requires.
    ///
    /// The rules mirror [`kontor_core::spec::ProjectSessionTopologySpec`]'s own
    /// validation rather than re-deciding them: `logical_only` is exclusive, a
    /// kind is not both root and child, and a `session_host` must materialize
    /// somewhere. Re-checking here is not redundant — a request assembled by
    /// hand never passed the specification validator, and this is the last point
    /// before a native effect.
    ///
    /// # Errors
    /// Returns [`RuntimeError::WorkspaceMismatch`] for an empty, contradictory
    /// or unmaterializable capability set.
    pub fn resolve(capabilities: &[NodeProjectionCapability]) -> RuntimeResult<Self> {
        let logical = capabilities.contains(&NodeProjectionCapability::LogicalOnly);
        let root = capabilities.contains(&NodeProjectionCapability::NativeRoot);
        let child = capabilities.contains(&NodeProjectionCapability::NativeChild);
        let host = capabilities.contains(&NodeProjectionCapability::SessionHost);

        if capabilities.is_empty() {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "a topology node declares no projection capability",
            });
        }
        if logical && capabilities.len() != 1 {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "logical_only is exclusive of every other projection capability",
            });
        }
        if root && child {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "a topology node cannot be both native_root and native_child",
            });
        }
        if host && !root && !child {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "a session_host must materialize as a native container",
            });
        }
        if logical {
            return Ok(Self::LogicalOnly);
        }
        if root {
            return Ok(Self::NativeRoot);
        }
        if child {
            return Ok(Self::NativeChild);
        }
        Err(RuntimeError::WorkspaceMismatch {
            rule: "a topology node declares no materializable projection capability",
        })
    }

    /// Whether this shape has a native container at all.
    #[must_use]
    pub const fn is_native(self) -> bool {
        matches!(self, Self::NativeRoot | Self::NativeChild)
    }
}

impl fmt::Display for ContainerProjection {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::LogicalOnly => "logical_only",
            Self::NativeRoot => "native_root",
            Self::NativeChild => "native_child",
        })
    }
}

/// Ask a runtime to make one topology node's native container exist and be
/// usable.
///
/// Every field that identifies something is a Kontor value. `display_name` and
/// `cwd` are what a runtime needs in order to *build* the container and to prove
/// it read back the right one; they are never how it is found again.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContainerRequest {
    /// The binding id Kontor has minted for this container.
    pub container_binding_id: ContainerBindingId,
    /// The node that owns the container. The only identity in this request.
    pub topology_node_id: TopologyNodeId,
    /// The immutable specification revision the node's kind was pinned from.
    pub topology: TopologySnapshot,
    /// The projection capabilities that revision assigns to the node's kind.
    pub capabilities: Vec<NodeProjectionCapability>,
    /// The name the native container should carry. Display, never identity.
    pub display_name: ExternalName,
    /// The exact native parent this container must be created below.
    ///
    /// Required by [`ContainerProjection::NativeChild`] and refused for every
    /// other shape: a child placed below "whatever project the adapter happens
    /// to hold" is the fallback this contract exists to make unspellable.
    pub parent: Option<ContainerBinding>,
    /// The canonical working directory, where the declared shape needs one.
    pub cwd: Option<WorkspaceRoot>,
    /// The native container Kontor already holds for this node, if any.
    ///
    /// This is the whole of the restart contract. A daemon restart destroys the
    /// adapter's own ledger while the native container carries on existing, so
    /// the only way back to it is the id Kontor persisted. An adapter that
    /// re-ran its first-binding search instead would either adopt by name —
    /// which is not identity — or create a second container beside the live one.
    ///
    /// Present means *reconcile*: read this exact id back and refuse if it is
    /// gone. It never means "prefer this one if you find it".
    pub bound_native_id: Option<ExternalId>,
    /// Optional delivery task reference. Tracker metadata only.
    pub task_id: Option<TaskId>,
    /// Optional delivery TeamRun reference. Tracker metadata only.
    pub team_run_id: Option<TeamRunId>,
    /// When preparation was requested.
    pub requested_at: Timestamp,
}

impl ContainerRequest {
    /// The label the runtime must report back for this container.
    #[must_use]
    pub const fn correlation(&self) -> ContainerLabel {
        ContainerLabel::for_node(self.topology_node_id)
    }

    /// The shape this request's capabilities require.
    ///
    /// # Errors
    /// Propagates [`ContainerProjection::resolve`].
    pub fn projection(&self) -> RuntimeResult<ContainerProjection> {
        ContainerProjection::resolve(&self.capabilities)
    }

    /// Prove the request is internally coherent before any native effect.
    ///
    /// # Errors
    /// Returns [`RuntimeError::WorkspaceMismatch`] for an unresolvable
    /// capability set, a child with no exact parent binding, a root or logical
    /// node carrying one, a parent binding that is not itself a native
    /// container, and a logical node carrying a working directory.
    pub fn validate(&self) -> RuntimeResult<ContainerProjection> {
        let projection = self.projection()?;
        match projection {
            ContainerProjection::LogicalOnly => {
                if self.parent.is_some() {
                    return Err(RuntimeError::WorkspaceMismatch {
                        rule: "a logical_only node has no native container to place",
                    });
                }
                if self.cwd.is_some() {
                    return Err(RuntimeError::WorkspaceMismatch {
                        rule: "a logical_only node has no native container to root",
                    });
                }
            }
            ContainerProjection::NativeRoot => {
                if self.parent.is_some() {
                    return Err(RuntimeError::WorkspaceMismatch {
                        rule: "a native_root is not created below another container",
                    });
                }
            }
            ContainerProjection::NativeChild => {
                let Some(parent) = &self.parent else {
                    return Err(RuntimeError::WorkspaceMismatch {
                        rule: "a native_child requires the exact native parent binding",
                    });
                };
                // A child below a logical parent has nowhere to be. Accepting it
                // is how a container ends up rooted at whatever the adapter last
                // touched.
                if !parent.projection.is_native() {
                    return Err(RuntimeError::WorkspaceMismatch {
                        rule: "a native_child requires a parent that is itself a native container",
                    });
                }
            }
        }
        Ok(projection)
    }
}

/// The binding between a topology node and one native container.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContainerBinding {
    /// The Kontor binding id.
    pub id: ContainerBindingId,
    /// The node that owns the container. Every lookup goes through this.
    pub topology_node_id: TopologyNodeId,
    /// The shape this container was bound as.
    pub projection: ContainerProjection,
    /// The native container. `native_id` is only meaningful inside
    /// `generation`.
    pub identity: NativeRuntimeIdentity,
    /// Where the container works, when its shape has a place.
    pub root: Option<WorkspaceRoot>,
    /// When it was bound.
    pub bound_at: Timestamp,
}

/// A container binding together with the evidence quality it was created under.
///
/// The capability snapshot is frozen exactly as it is for a session or workspace
/// binding: a later adapter upgrade cannot retroactively improve what an earlier
/// placement was allowed to assume.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContainerBindingSnapshot {
    /// The binding.
    pub binding: ContainerBinding,
    /// The capabilities discovered when the binding was created.
    pub capabilities: RuntimeCapabilities,
    /// Proof that this native container belongs to this topology node.
    pub correlation: ContainerCorrelationEvidence,
}

impl ContainerBindingSnapshot {
    /// The Kontor binding id.
    #[must_use]
    pub const fn binding_id(&self) -> ContainerBindingId {
        self.binding.id
    }

    /// The node this container belongs to.
    #[must_use]
    pub const fn topology_node_id(&self) -> TopologyNodeId {
        self.binding.topology_node_id
    }

    /// Where this container lives, when its shape has a place.
    #[must_use]
    pub const fn root(&self) -> Option<&WorkspaceRoot> {
        self.binding.root.as_ref()
    }

    /// Prove the snapshot's own parts agree with each other.
    ///
    /// A container binding is only evidence if the correlation travelling inside
    /// it is evidence *for that binding*. A snapshot whose label names another
    /// node, or whose correlation was established against another native
    /// container, proves nothing about the place it claims.
    ///
    /// # Errors
    /// Returns [`RuntimeError::CorrelationFailed`] when the correlation does not
    /// belong to the binding it travels with.
    pub fn ensure_correlated(&self) -> RuntimeResult<()> {
        if self.correlation.label.topology_node_id() != self.binding.topology_node_id
            || self.correlation.native != self.binding.identity
        {
            return Err(RuntimeError::CorrelationFailed);
        }
        Ok(())
    }

    /// Prove this container was prepared for exactly this topology node.
    ///
    /// # Errors
    /// Returns [`RuntimeError::WorkspaceMismatch`] when the binding belongs to
    /// another node.
    pub fn ensure_node(&self, topology_node_id: TopologyNodeId) -> RuntimeResult<()> {
        if self.binding.topology_node_id != topology_node_id {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "the container was prepared for another topology node",
            });
        }
        Ok(())
    }

    /// Prove the container still exists in the runtime's current generation.
    ///
    /// # Errors
    /// Returns [`RuntimeError::StaleBinding`] after a runtime restart. A native
    /// container id may repeat across generations; the binding does not.
    pub const fn ensure_generation(&self, current: u64) -> RuntimeResult<()> {
        if self.binding.identity.generation == current {
            return Ok(());
        }
        Err(RuntimeError::StaleBinding {
            rule: "the runtime generation changed since this container was prepared",
        })
    }

    /// Prove a caller is about to work where the container actually is.
    ///
    /// # Errors
    /// Returns [`RuntimeError::WorkspaceMismatch`] when the claimed working
    /// directory is not this container's root, and when the container has no
    /// root to claim at all.
    pub fn ensure_root(&self, claimed: &WorkspaceRoot) -> RuntimeResult<()> {
        let Some(root) = &self.binding.root else {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "this container has no working directory to claim",
            });
        };
        if root != claimed {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "the claimed working directory is not the verified container root",
            });
        }
        Ok(())
    }
}

/// What preparing a container produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContainerOutcome {
    /// The binding every later placement below this node must present.
    pub snapshot: ContainerBindingSnapshot,
    /// Whether this call created the container. A repeated preparation for the
    /// same node returns the original binding with `created = false`.
    pub created: bool,
}

#[cfg(test)]
mod tests {
    use kontor_core::id::{ContentHash, SpecVersion, TopologySpecId};

    use super::*;
    use crate::capability::{RuntimeCapability, RuntimeLimits, TrustGrade};

    fn snapshot() -> TopologySnapshot {
        TopologySnapshot {
            spec_id: TopologySpecId::generate(),
            version: SpecVersion::FIRST,
            canonical_hash: ContentHash::parse(&"a".repeat(64)).expect("a canonical hash"),
        }
    }

    fn identity(native_id: &str) -> NativeRuntimeIdentity {
        NativeRuntimeIdentity {
            runtime_kind: kontor_core::id::RuntimeKindKey::parse("paseo.agent")
                .expect("a runtime kind"),
            host: ExternalName::parse("paseo-local").expect("a host"),
            generation: 1,
            native_id: kontor_core::id::ExternalId::parse(native_id).expect("a native id"),
        }
    }

    fn request(
        node: TopologyNodeId,
        capabilities: Vec<NodeProjectionCapability>,
    ) -> ContainerRequest {
        ContainerRequest {
            container_binding_id: ContainerBindingId::generate(),
            topology_node_id: node,
            topology: snapshot(),
            capabilities,
            display_name: ExternalName::parse("Epic · ASMA-7871").expect("a display name"),
            parent: None,
            cwd: None,
            bound_native_id: None,
            task_id: None,
            team_run_id: None,
            requested_at: Timestamp::now(),
        }
    }

    fn binding(node: TopologyNodeId, projection: ContainerProjection) -> ContainerBinding {
        ContainerBinding {
            id: ContainerBindingId::generate(),
            topology_node_id: node,
            projection,
            identity: identity("prj_da432f9269aa936f"),
            root: None,
            bound_at: Timestamp::now(),
        }
    }

    #[test]
    fn a_native_container_id_cannot_be_read_as_a_kontor_identifier() {
        assert!(ContainerLabel::parse("prj_da432f9269aa936f").is_err());
        assert!(ContainerBindingId::parse("prj_da432f9269aa936f").is_err());
    }

    #[test]
    fn a_label_round_trips_through_the_node_it_names() {
        let node = TopologyNodeId::generate();
        let label = ContainerLabel::for_node(node);
        assert_eq!(
            ContainerLabel::parse(&label.to_string())
                .expect("a Kontor label")
                .topology_node_id(),
            node
        );
    }

    #[test]
    fn a_projection_is_resolved_from_capabilities_and_never_from_a_kind_name() {
        assert_eq!(
            ContainerProjection::resolve(&[NodeProjectionCapability::LogicalOnly])
                .expect("a logical node"),
            ContainerProjection::LogicalOnly
        );
        assert_eq!(
            ContainerProjection::resolve(&[
                NodeProjectionCapability::NativeRoot,
                NodeProjectionCapability::SessionHost,
            ])
            .expect("a hosting root"),
            ContainerProjection::NativeRoot
        );
        assert_eq!(
            ContainerProjection::resolve(&[NodeProjectionCapability::NativeChild])
                .expect("a child"),
            ContainerProjection::NativeChild
        );
    }

    #[test]
    fn an_incoherent_capability_set_is_refused_rather_than_guessed() {
        for capabilities in [
            vec![],
            vec![
                NodeProjectionCapability::LogicalOnly,
                NodeProjectionCapability::SessionHost,
            ],
            vec![
                NodeProjectionCapability::NativeRoot,
                NodeProjectionCapability::NativeChild,
            ],
            vec![NodeProjectionCapability::SessionHost],
        ] {
            assert!(
                ContainerProjection::resolve(&capabilities).is_err(),
                "{capabilities:?} does not name one buildable shape"
            );
        }
    }

    #[test]
    fn a_child_requires_the_exact_native_parent_binding() {
        let node = TopologyNodeId::generate();
        let orphan = request(node, vec![NodeProjectionCapability::NativeChild]);
        assert_eq!(
            orphan
                .validate()
                .expect_err("a child with no parent has nowhere to be"),
            RuntimeError::WorkspaceMismatch {
                rule: "a native_child requires the exact native parent binding"
            }
        );

        let mut adopted = request(node, vec![NodeProjectionCapability::NativeChild]);
        adopted.parent = Some(binding(
            TopologyNodeId::generate(),
            ContainerProjection::NativeRoot,
        ));
        assert_eq!(
            adopted.validate().expect("a child below a native root"),
            ContainerProjection::NativeChild
        );

        // A logical parent is not a place, however well-formed the binding is.
        let mut below_logical = request(node, vec![NodeProjectionCapability::NativeChild]);
        below_logical.parent = Some(binding(
            TopologyNodeId::generate(),
            ContainerProjection::LogicalOnly,
        ));
        assert!(below_logical.validate().is_err());
    }

    #[test]
    fn a_root_and_a_logical_node_refuse_a_parent() {
        let node = TopologyNodeId::generate();
        for capability in [
            NodeProjectionCapability::NativeRoot,
            NodeProjectionCapability::LogicalOnly,
        ] {
            let mut parented = request(node, vec![capability]);
            parented.parent = Some(binding(
                TopologyNodeId::generate(),
                ContainerProjection::NativeRoot,
            ));
            assert!(
                parented.validate().is_err(),
                "{capability:?} is not created below another container"
            );
        }
    }

    #[test]
    fn a_snapshot_whose_correlation_names_another_node_is_not_evidence() {
        let node = TopologyNodeId::generate();
        let other = TopologyNodeId::generate();
        let now = Timestamp::now();
        let snapshot = ContainerBindingSnapshot {
            binding: binding(node, ContainerProjection::NativeRoot),
            capabilities: RuntimeCapabilities {
                trust_grade: TrustGrade::A,
                supported: RuntimeCapability::ALL.iter().copied().collect(),
                account_env: false,
                limits: RuntimeLimits {
                    max_message_bytes: 1_024,
                    max_history_page: 10,
                    max_concurrent_sessions: 1,
                    context_window: kontor_core::spec::ContextWindowBounds::unknown(),
                },
            },
            correlation: ContainerCorrelationEvidence {
                label: ContainerLabel::for_node(other),
                native: identity("prj_da432f9269aa936f"),
                established_at: now,
            },
        };
        assert_eq!(
            snapshot
                .ensure_correlated()
                .expect_err("the correlation belongs to another node"),
            RuntimeError::CorrelationFailed
        );
        assert!(snapshot.ensure_node(other).is_err());
        assert!(snapshot.ensure_node(node).is_ok());
    }
}
