//! Task-scoped runtime workspaces.
//!
//! A team run works in **one** verified place. Every role of a same-runtime team
//! reuses the same task workspace binding, and a role that claims a different
//! working directory is refused *before* it can edit anything — a wrong-workspace
//! edit is not recoverable by observing it afterwards.
//!
//! The binding here is the exact parallel of the session binding in
//! [`crate::capability::RuntimeBindingSnapshot`]: a Kontor identifier, a native
//! identity that is only meaningful inside one runtime generation, frozen
//! capabilities, and correlation evidence tying the native workspace back to the
//! team run that asked for it. A native workspace id never becomes a Kontor id.

use std::fmt;

use kontor_core::id::{ExternalName, TaskId, TeamRunId, Timestamp};
use kontor_core::state::NativeRuntimeIdentity;
use kontor_core::{DomainError, DomainResult};
use uuid::Uuid;

use crate::adapter::{RuntimeError, RuntimeResult};
use crate::capability::RuntimeCapabilities;
use crate::request::parse_kontor_uuid;

/// The prefix every Kontor workspace correlation label carries.
pub const WORKSPACE_CORRELATION_PREFIX: &str = "kontor-team-";

/// Identifies the binding between a team run and a native task workspace.
///
/// A time-ordered UUID v7 generated by Kontor and rendered as lowercase
/// hyphenated text.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct WorkspaceBindingId(Uuid);

impl WorkspaceBindingId {
    /// Generate a fresh, time-ordered identifier.
    #[must_use]
    pub fn generate() -> Self {
        Self(kontor_core::id::generate_uuid_v7())
    }

    /// Parse the canonical lowercase hyphenated text form.
    ///
    /// # Errors
    /// Rejects any non-canonical spelling and any UUID that is not version 7,
    /// which is what stops a native workspace id from being read as one.
    pub fn parse(text: &str) -> DomainResult<Self> {
        parse_kontor_uuid("WorkspaceBindingId", text).map(Self)
    }

    /// Borrow the underlying UUID.
    #[must_use]
    pub const fn as_uuid(&self) -> &Uuid {
        &self.0
    }
}

impl fmt::Display for WorkspaceBindingId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Display::fmt(&self.0.as_hyphenated(), f)
    }
}

/// An absolute path a runtime will actually work in.
///
/// The one difference between two spellings that is *not* a difference is a
/// trailing separator: `/w/task` and `/w/task/` are the same place. Everything
/// else that makes one place readable as two distinct values is refused rather
/// than resolved — a relative path, an empty component from a repeated
/// separator, `.`, and `..`.
///
/// Refusing rather than resolving is deliberate. Every workspace guard rail
/// compares these as values, so a path that lands somewhere other than it reads
/// defeats them: `/runtime/task/..` is the runtime root while comparing unequal
/// to it. Resolving `..` textually would be the wrong repair, because it is
/// simply false across a symlink.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct WorkspaceRoot(ExternalName);

impl WorkspaceRoot {
    /// Parse and normalize an absolute workspace path.
    ///
    /// # Errors
    /// Returns [`DomainError::Invalid`] for a relative path, for any non-normal
    /// component, and for anything [`ExternalName::parse`] refuses.
    pub fn parse(text: &str) -> DomainResult<Self> {
        let Some(body) = text.strip_prefix('/') else {
            return Err(DomainError::invalid(
                "WorkspaceRoot",
                "must be an absolute path",
            ));
        };
        if body.is_empty() {
            // The filesystem root, which is a place even though it has no
            // components of its own.
            return ExternalName::parse("/").map(Self);
        }
        // Exactly *one* trailing separator is the spelling difference that is
        // not a difference. Trimming every trailing separator instead would
        // quietly normalize `/w//` and `/w/task///`, which are repeated
        // separators — the very thing the component check below refuses.
        let body = body.strip_suffix('/').unwrap_or(body);
        if body
            .split('/')
            .any(|component| matches!(component, "" | "." | ".."))
        {
            return Err(DomainError::invalid(
                "WorkspaceRoot",
                "must be normalized: no empty, `.` or `..` path component",
            ));
        }
        ExternalName::parse(&format!("/{body}")).map(Self)
    }

    /// Borrow the normalized path text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        self.0.as_str()
    }

    /// Refuse a task workspace that is the runtime's shared root.
    ///
    /// A task workspace exists to isolate one team run's edits. Handing back the
    /// shared root instead would satisfy every later check while quietly
    /// removing the isolation the guardrails depend on.
    ///
    /// # Errors
    /// Returns [`RuntimeError::WorkspaceMismatch`] when the two are the same
    /// place.
    pub fn ensure_task_scoped(&self, runtime_root: &Self) -> RuntimeResult<()> {
        if self == runtime_root {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "a task workspace must not be the runtime root",
            });
        }
        Ok(())
    }
}

impl fmt::Display for WorkspaceRoot {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A label Kontor plants so a native workspace can be tied back to the team run
/// that asked for it.
///
/// The label *is* a [`TeamRunId`] by construction, so a native workspace id can
/// never be parsed into one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct WorkspaceLabel(TeamRunId);

impl WorkspaceLabel {
    /// The label for one team run.
    #[must_use]
    pub const fn for_team_run(team_run_id: TeamRunId) -> Self {
        Self(team_run_id)
    }

    /// Parse a label a runtime reported back.
    ///
    /// # Errors
    /// Returns [`DomainError::Invalid`] when the text is not the Kontor prefix
    /// followed by a canonical [`TeamRunId`].
    pub fn parse(text: &str) -> DomainResult<Self> {
        let tail = text
            .strip_prefix(WORKSPACE_CORRELATION_PREFIX)
            .ok_or_else(|| {
                DomainError::invalid("WorkspaceLabel", "does not carry the Kontor team prefix")
            })?;
        TeamRunId::parse(tail).map(Self)
    }

    /// The team run this label names.
    #[must_use]
    pub const fn team_run_id(self) -> TeamRunId {
        self.0
    }
}

impl fmt::Display for WorkspaceLabel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{WORKSPACE_CORRELATION_PREFIX}{}", self.0)
    }
}

/// Proof that a native workspace belongs to the team run that asked for it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceCorrelationEvidence {
    /// The Kontor label the runtime reported back.
    pub label: WorkspaceLabel,
    /// The native workspace that reported it. Evidence, never identity.
    pub native: NativeRuntimeIdentity,
    /// When the correlation was established.
    pub established_at: Timestamp,
}

impl WorkspaceCorrelationEvidence {
    /// Establish correlation from what a runtime reported.
    ///
    /// # Errors
    /// Returns [`RuntimeError::CorrelationFailed`] when the runtime did not
    /// report this team run's label.
    pub fn establish(
        team_run_id: TeamRunId,
        reported: &str,
        native: NativeRuntimeIdentity,
        established_at: Timestamp,
    ) -> RuntimeResult<Self> {
        let label = WorkspaceLabel::for_team_run(team_run_id);
        if reported != label.to_string() {
            return Err(RuntimeError::CorrelationFailed);
        }
        Ok(Self {
            label,
            native,
            established_at,
        })
    }
}

/// The binding between a team run and one native task workspace.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceBinding {
    /// The Kontor binding id.
    pub id: WorkspaceBindingId,
    /// The team run that owns the workspace. Every role of that run shares it.
    pub team_run_id: TeamRunId,
    /// The task the workspace serves.
    pub task_id: TaskId,
    /// Where the work actually happens.
    pub root: WorkspaceRoot,
    /// The native workspace. `native_id` names a workspace rather than a
    /// session, and is only meaningful inside `generation`.
    pub identity: NativeRuntimeIdentity,
    /// When it was bound.
    pub bound_at: Timestamp,
}

/// A workspace binding together with the evidence quality it was created under.
///
/// The capability snapshot is frozen exactly as it is for a session binding: a
/// later adapter upgrade cannot retroactively improve what an earlier team run
/// was allowed to assume about its workspace.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceBindingSnapshot {
    /// The binding.
    pub binding: WorkspaceBinding,
    /// The capabilities discovered when the binding was created.
    pub capabilities: RuntimeCapabilities,
    /// Proof that this native workspace belongs to this team run.
    pub correlation: WorkspaceCorrelationEvidence,
}

impl WorkspaceBindingSnapshot {
    /// The Kontor binding id.
    #[must_use]
    pub const fn binding_id(&self) -> WorkspaceBindingId {
        self.binding.id
    }

    /// Where this workspace lives.
    #[must_use]
    pub const fn root(&self) -> &WorkspaceRoot {
        &self.binding.root
    }

    /// Prove the snapshot's own parts agree with each other.
    ///
    /// A workspace binding is only evidence if the correlation travelling
    /// inside it is evidence *for that binding*. A snapshot whose label names
    /// another team run, or whose correlation was established against another
    /// native workspace, proves nothing about the place it claims — and it is
    /// exactly what a fabricated snapshot looks like, since forging one costs
    /// nothing while re-deriving consistent correlation costs the runtime.
    ///
    /// # Errors
    /// Returns [`RuntimeError::CorrelationFailed`] when the correlation does
    /// not belong to the binding it travels with.
    pub fn ensure_correlated(&self) -> RuntimeResult<()> {
        if self.correlation.label.team_run_id() != self.binding.team_run_id
            || self.correlation.native != self.binding.identity
        {
            return Err(RuntimeError::CorrelationFailed);
        }
        Ok(())
    }

    /// Prove the workspace still exists in the runtime's current generation.
    ///
    /// # Errors
    /// Returns [`RuntimeError::StaleBinding`] after a runtime restart. A native
    /// workspace id may repeat across generations; the binding does not.
    pub const fn ensure_generation(&self, current: u64) -> RuntimeResult<()> {
        if self.binding.identity.generation == current {
            return Ok(());
        }
        Err(RuntimeError::StaleBinding {
            rule: "the runtime generation changed since this workspace was prepared",
        })
    }

    /// Prove this workspace was prepared for exactly this team run and task.
    ///
    /// # Errors
    /// Returns [`RuntimeError::WorkspaceMismatch`] when a role presents another
    /// team run's or another task's workspace.
    pub fn ensure_scope(&self, team_run_id: TeamRunId, task_id: TaskId) -> RuntimeResult<()> {
        if self.binding.team_run_id != team_run_id {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "the workspace was prepared for another team run",
            });
        }
        if self.binding.task_id != task_id {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "the workspace was prepared for another task",
            });
        }
        Ok(())
    }

    /// Prove a role is about to work where the workspace actually is.
    ///
    /// # Errors
    /// Returns [`RuntimeError::WorkspaceMismatch`] when the claimed working
    /// directory is not the bound workspace root.
    pub fn ensure_root(&self, claimed: &WorkspaceRoot) -> RuntimeResult<()> {
        if &self.binding.root != claimed {
            return Err(RuntimeError::WorkspaceMismatch {
                rule: "the claimed working directory is not the verified task workspace",
            });
        }
        Ok(())
    }
}

/// What a role claims about where it will work.
///
/// Passing one of these to [`crate::capability::preflight`] is how a launch
/// proves it goes through a verified workspace. A `binding` of `None` against a
/// runtime that prepares workspaces is a launch that skipped preparation, and is
/// refused.
#[derive(Debug, Clone, Copy)]
pub struct WorkspaceClaim<'a> {
    /// The verified workspace binding, when the caller has one.
    pub binding: Option<&'a WorkspaceBindingSnapshot>,
    /// The team run the role belongs to.
    pub team_run_id: TeamRunId,
    /// The task the role serves.
    pub task_id: TaskId,
    /// Where the role says it will work.
    pub cwd: &'a WorkspaceRoot,
}

impl WorkspaceClaim<'_> {
    /// Verify the claim before anything can be edited.
    ///
    /// # Errors
    /// * [`RuntimeError::WorkspaceBindingRequired`] — no binding at all.
    /// * [`RuntimeError::CorrelationFailed`] — a binding whose correlation does
    ///   not belong to it.
    /// * [`RuntimeError::WorkspaceMismatch`] — another team run's or task's
    ///   workspace, or a working directory that is not the bound root.
    /// * [`RuntimeError::StaleBinding`] — the runtime restarted since it was
    ///   prepared.
    pub fn verify(&self, current_generation: Option<u64>) -> RuntimeResult<()> {
        let Some(snapshot) = self.binding else {
            return Err(RuntimeError::WorkspaceBindingRequired);
        };
        // Before the binding is read as evidence for anything, it has to be
        // evidence at all.
        snapshot.ensure_correlated()?;
        snapshot.ensure_scope(self.team_run_id, self.task_id)?;
        snapshot.ensure_root(self.cwd)?;
        if let Some(generation) = current_generation {
            snapshot.ensure_generation(generation)?;
        }
        Ok(())
    }
}

/// Ask a runtime to make a team run's task workspace exist and be usable.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspacePrepareRequest {
    /// The team run the workspace belongs to.
    pub team_run_id: TeamRunId,
    /// The task it serves.
    pub task_id: TaskId,
    /// The binding id Kontor has minted for it.
    pub workspace_binding_id: WorkspaceBindingId,
    /// Where the workspace must be.
    pub root: WorkspaceRoot,
    /// When preparation was requested.
    pub requested_at: Timestamp,
}

impl WorkspacePrepareRequest {
    /// The label the runtime must report back for this workspace.
    #[must_use]
    pub const fn correlation(&self) -> WorkspaceLabel {
        WorkspaceLabel::for_team_run(self.team_run_id)
    }
}

/// What preparing a workspace produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceOutcome {
    /// The binding every role of the team run must present.
    pub snapshot: WorkspaceBindingSnapshot,
    /// Whether this call created the workspace. A repeated preparation for the
    /// same team run returns the original binding with `created = false`.
    pub created: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_workspace_root_is_absolute_and_normalized() {
        assert!(WorkspaceRoot::parse("relative/path").is_err());
        let with_slash = WorkspaceRoot::parse("/w/task-1/").expect("absolute path");
        let without_slash = WorkspaceRoot::parse("/w/task-1").expect("absolute path");
        assert_eq!(with_slash, without_slash);
        assert_eq!(with_slash.as_str(), "/w/task-1");
    }

    #[test]
    fn a_non_normal_spelling_is_refused_rather_than_resolved() {
        for spelling in [
            "/w/task-1/..",
            "/w/task-1/.",
            "/w/../task-1",
            "//w/task-1",
            "/w//task-1",
            "/..",
            "/.",
        ] {
            assert!(
                WorkspaceRoot::parse(spelling).is_err(),
                "{spelling} reads as one place and lands in another"
            );
        }
        // The filesystem root itself is still a spellable place.
        assert_eq!(
            WorkspaceRoot::parse("/")
                .expect("the root is absolute")
                .as_str(),
            "/"
        );
    }

    #[test]
    fn a_doubled_separator_is_still_refused() {
        // A repeated separator is an empty component wherever it sits. Refusing
        // it only in the middle and collapsing it at the end would make one
        // place spellable two ways again — the exact defect the guard rails
        // compare their way into.
        for spelling in ["/w//", "/w/task-1///", "/w/task-1//", "//", "///"] {
            assert!(
                WorkspaceRoot::parse(spelling).is_err(),
                "{spelling} carries an empty component and must not normalize"
            );
        }
        // One trailing separator remains the single spelling that is not a
        // difference.
        assert_eq!(
            WorkspaceRoot::parse("/w/task-1/")
                .expect("a single trailing separator is the same place")
                .as_str(),
            "/w/task-1"
        );
    }

    #[test]
    fn a_task_workspace_is_never_the_runtime_root() {
        let root = WorkspaceRoot::parse("/w").expect("absolute path");
        let task = WorkspaceRoot::parse("/w/task-1").expect("absolute path");
        assert!(task.ensure_task_scoped(&root).is_ok());
        assert_eq!(
            root.ensure_task_scoped(&root)
                .expect_err("the shared root is not a task workspace"),
            RuntimeError::WorkspaceMismatch {
                rule: "a task workspace must not be the runtime root"
            }
        );
        // The runtime root under any spelling it actually has is still itself.
        assert_eq!(
            WorkspaceRoot::parse("/w/")
                .expect("a trailing separator is the same place")
                .ensure_task_scoped(&root)
                .expect_err("an aliased runtime root is still the runtime root"),
            RuntimeError::WorkspaceMismatch {
                rule: "a task workspace must not be the runtime root"
            }
        );
        // And the spelling that would otherwise slip past it does not exist.
        assert!(WorkspaceRoot::parse("/w/task-1/..").is_err());
    }

    #[test]
    fn a_native_workspace_id_cannot_be_read_as_a_kontor_identifier() {
        assert!(WorkspaceLabel::parse("wks_d01f8712c1b5363a").is_err());
        assert!(WorkspaceBindingId::parse("wks_d01f8712c1b5363a").is_err());
    }
}
